apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8-sample
  labels:
    app: static
spec:
  replicas: 2
  selector:
    matchLabels:
      app: static
  template:
    metadata:
      labels:
        app: static
    spec:
      containers:
      - name: static
        image: 274401088258.dkr.ecr.ap-southeast-1.amazonaws.com/k8s-static
        ports:
        - containerPort: 80
