apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8-sample
  labels:
    app: static
spec:
  replicas: 2
  selector:
    matchLabels:
      app: static
  template:
    metadata:
      labels:
        app: static
    spec:
      containers:
      - name: static
        image: 861531569385.dkr.ecr.eu-west-2.amazonaws.com/k8s-sample:6
        ports:
        - containerPort: 80
