apiVersion: v1
kind: Service
metadata:
  name: k8-sample-Service
  namespeace: static
spec:
  selector:
    app: static
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      type: loadbalancer
